BASE_URL = " https://www.saucedemo.com/"
username_id = "user-name"
password_id = "password"
login_button_id = "login-button"
errorMessage_Invalidtext = "Epic sadface: Username and password do not match any user in this service"
errorMessage_InvalidXpath = "//*[@id='login_button_container']/div/form/div[3]/h3"  
errorMessage_blankXpath = "//*[@id='login_button_container']/div/form/div[3]/h3"
errorMessage_blanktext = "Epic sadface: Username is required"
userNameBlank = ""
passwordBlank = ""
userName = "Emine Coskun"
errorMessage_blankPasswordXpath = "//*[@id='login_button_container']/div/form/div[3]/h3"
errorMessage_blankPasswordtext = "Epic sadface: Password is required"
lokedUserName = "locked_out_user"
validPassword = "secret_sauce"
errorMessage_lokedUserdXpath = "//*[@id='login_button_container']/div/form/div[3]/h3"
errorMessage_lokedUsertext = "Epic sadface: Sorry, this user has been locked out."
validUserName = "standard_user"
baslikXpath = "//div[@class='app_logo']"
baslikText = "Swag Labs"
productListXpat = "div[class='inventory_item']"

